version: '3'

services:
  db:
    image: mariadb:10.3
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-php7.3-apache
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: mypassword
    working_dir: /var/www/html
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: /home/vagrant/data/mysql-data
      o: bind
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: /home/vagrant/data/wordpress-data
      o: bind